/**
 * @file rt_evento_t.h
 * @ingroup RT_EVENT
 * @brief Event Types Definition
 * @details Defines the event types that can be handled by the real-time system.
 *          Each event represents a specific action or occurrence that needs to
 *          be processed by the system.
 *
 * Hardware Project 2024
 * EINA - University of Zaragoza
 *
 * @author Víctor Orrios Barón (840994)
 * @author José Miguel Quílez Vergara (873499)
 * @date 17/12/2024
 */

#ifndef RT_EVENTO
#define RT_EVENTO

/**
 * @brief Event types supported by the system
 * 
 * @note The numeric values are important and must not be modified
 * as they are used as array indices.
 */
typedef enum {
    /** @brief Null event. Used as default value or to indicate absence of event */
    ev_VOID = 0,

    /** @brief Periodic timing event. Generated by the alarm system for periodic tasks */
    ev_T_PERIODICO = 1,

    /** @brief Button press event. Generated when a valid button press is detected */
    ev_PULSAR_BOTON = 2,

    /** @brief User inactivity event. Generated when no interaction is detected for a defined period */
    ev_INACTIVIDAD = 3,

    /** @brief Delay event. Used to implement non-blocking delays in the system */
    ev_RETARDO = 4,

    /** @brief LED blink event. Controls LED blinking timing */
    ev_BLINK = 5,

    /** @brief Watchdog feed event. Used in watchdog timer implementation */
    ev_WDT = 6,

    /** @brief Counter Strike game event. Manages game logic for Counter Strike */
    ev_COUNTER_STRIKE = 7,

    /** @brief Generic test event. Can be used by all test modules */
    ev_TEST = 8,

    /** @brief Simon Says game event. Manages game logic for Simon Says */
    ev_SIMON_GENERICO = 9,

    /** @brief Watchdog feed event. Similar to ev_WDT, used for watchdog timer reset */
    ev_FEED_WDT = 10,

    /** @brief Double button press event. Generated when two buttons are pressed simultaneously */
    ev_DOBLE_BOTON_PULSADO = 11,

    /** @brief Button debounce alarm event. Enables button anti-bounce protection */
    ev_ENABLE_BUTTON_REBOUNCE_ALARM = 12,

    /** @brief Counter Strike test event. Used for game testing procedures */
    ev_TEST_CS_MAIN = 13,

    /** @brief Statistics dump event. Generates a complete system status report */
    ev_DUMP_ALL_STATS = 14,

    /** @brief UART available event. Indicates UART is free and ready for use */
    ev_UART_FREED = 15
} EVENTO_T; // maps to uint32_t

/**
 * @brief Total number of event types defined in the system
 * 
 * This value must be updated when new event types are added
 * to the EVENTO_T enumeration.
 */
#define EVENT_TYPES 16

/**
 * @brief Number of user-triggered events in the system
 * 
 * Defines the total count of events that can be directly triggered by user interaction.
 * Currently only includes button press events.
 */
#define ev_NUM_EV_USUARIO 1

/**
 * @brief Array of user-triggered event types
 * 
 * Contains all event types that can be directly triggered by user interaction.
 * Used for event filtering and user input processing.
 */
#define ev_USUARIO {ev_PULSAR_BOTON}

#endif
